language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

cache: pip
install: pip install -e .[tests]
script: pytest --cov src
after_success:
  - coveralls

matrix:
  allow_failures:
    - python: "3.6"
    - python: "3.9"
